[package]
name = "calc-engine"
version = "0.1.0"
authors = ["Martin Suesskraut <22873554+msuesskraut@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
